Hello microverse project pull request
igna10697/Hello pull request #1
Opened 2023-01-11 07:41 UTC by igna10697

2023-01-11 07:44 UTC, igna10697 commented
This is a simple html and css project

2023-01-11 08:30 UTC, iambenkis requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @igna10697  👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

## To Highlight 🎉 

- Gitflow is followed. :heavy_check_mark:
- Well implemented HTML and CSS. :heavy_check_mark: 
- Meaningful commit sentences :heavy_check_mark: 

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️

- [ ] Good job @igna10697   :+1:  setting everything up, but your PR summary should be more description as required . :100: , Kindly follow this [example](https://github.com/iambenkis/Space-X-/pull/32) to see what it looks like. And update yours.

![Screenshot from 2023-01-11 10-16-19](https://user-images.githubusercontent.com/80458199/211754002-1c22affa-60d3-4cde-a126-718517279bfa.png)

- [ ] I acknowledge your effort setting up linters :pray: , unfortunately all the linters you set should have passed. Kindly make sure all your linters passed :100: 

I suggest you to run this command to solve them : 
```bash
npx stylelint css/styles.css --fix
```
For more information about style lint look [here](https://medium.com/@mrjohnkilonzi/how-to-css-lint-auto-fix-using-stickler-and-stylelint-37b52693d449)

- [ ] I noticed that your README file is not on the correct branch, and when you are going to merge your branches, the content that will be considered is the content of the README file on the `htmlcss_branch` branch. Kindly make sure you have a well documented README file on the feature branch. :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@iambenkis** in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 08:30 UTC, iambenkis commented on index.html
> +</html>
- [ ] Keep doing the great work :clap:

2023-01-11 08:30 UTC, iambenkis commented on style.css
> +}
- [ ] Keep doing the great work :clap:

2023-01-13 13:35 UTC, NduatiKagiri reviewed
Hi @igna10697 , 

# INVALID REVIEW REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where some Linters checks are not passing, and you have not made changes to your README as requested by the previous reviewer.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-13 14:59 UTC, merged